/* eslint-disable max-len */
import {GlobalKeywords} from './util';
import {_borderShorthand} from './validation-complex.js';

const _autoNone = 'auto | none';
const _borderTopRadius = '<border-top-radius>';
const _color = '<color>';
const _cornerShapeValue = '<corner-shape-value>';
const _cornerTop = '<corner-top>';
const _cornerTopLeft = '<corner-top-left>';
const _cornerTopShape = '<corner-top-shape>';
const _insetValue = '<inset-value>';
const _insetValue1or2 = _insetValue + '{1,2}';
const _lenPct0plus = '<len-pct0+>';
const _lenPct1or2 = '<len-pct>{1,2}';
const _lineStyle = '<line-style>';
const _lineWidth = '<line-width>';
const _ruleVisibilityItems = 'all | around | between | normal';
const _width = '<width>';

const Properties = {
  __proto__: null,
  'accent-color': 'auto | <color>',
  'align-items': 'normal | stretch | anchor-center | <baseline-position> | <overflow-position>? <self-position>',
  'align-content': 'normal | <baseline-position> | <content-distribution> | <overflow-position>? <content-position>',
  'align-self': 'auto | <align-items>',
  'all': GlobalKeywords.join('|'),
  'alignment-baseline': 'auto | baseline | use-script | before-edge | text-before-edge | ' +
    'after-edge | text-after-edge | central | middle | ideographic | alphabetic | ' +
    'hanging | mathematical',
  'anchor-name': 'none | <dashed-ident>#',
  'anchor-scope': 'none | all | <dashed-ident>#',
  'animation': '[ <time0+> || <timing-function> || <time> || [ infinite | <num0+> ] || ' +
    '<animation-direction> || <animation-fill-mode> || ' +
    '[ running | paused ] || [ none | <custom-ident> | <string> ] || <animation-timeline> ]#',
  'animation-composition': '[ replace | add | accumulate ]#',
  'animation-delay': '<time>#',
  'animation-direction': '<animation-direction>#',
  'animation-duration': '[ auto | <time0+> ]#',
  'animation-fill-mode': '<animation-fill-mode>#',
  'animation-iteration-count': '[ <num> | infinite ]#',
  'animation-name': '[ none | <keyframes-name> ]#',
  'animation-play-state': '[ running | paused ]#',
  'animation-timeline': '<animation-timeline>#',
  'animation-timing-function': '<timing-function>#',
  'appearance': 'none | auto',
  '-moz-appearance': 'none | button | button-arrow-down | button-arrow-next | button-arrow-previous | button-arrow-up | button-bevel | button-focus | caret | checkbox | checkbox-container | checkbox-label | checkmenuitem | dualbutton | groupbox | listbox | listitem | menuarrow | menubar | menucheckbox | menuimage | menuitem | menuitemtext | menulist | menulist-button | menulist-text | menulist-textfield | menupopup | menuradio | menuseparator | meterbar | meterchunk | progressbar | progressbar-vertical | progresschunk | progresschunk-vertical | radio | radio-container | radio-label | radiomenuitem | range | range-thumb | resizer | resizerpanel | scale-horizontal | scalethumbend | scalethumb-horizontal | scalethumbstart | scalethumbtick | scalethumb-vertical | scale-vertical | scrollbarbutton-down | scrollbarbutton-left | scrollbarbutton-right | scrollbarbutton-up | scrollbarthumb-horizontal | scrollbarthumb-vertical | scrollbartrack-horizontal | scrollbartrack-vertical | searchfield | separator | sheet | spinner | spinner-downbutton | spinner-textfield | spinner-upbutton | splitter | statusbar | statusbarpanel | tab | tabpanel | tabpanels | tab-scroll-arrow-back | tab-scroll-arrow-forward | textfield | textfield-multiline | toolbar | toolbarbutton | toolbarbutton-dropdown | toolbargripper | toolbox | tooltip | treeheader | treeheadercell | treeheadersortarrow | treeitem | treeline | treetwisty | treetwistyopen | treeview | -moz-mac-unified-toolbar | -moz-win-borderless-glass | -moz-win-browsertabbar-toolbox | -moz-win-communicationstext | -moz-win-communications-toolbox | -moz-win-exclude-glass | -moz-win-glass | -moz-win-mediatext | -moz-win-media-toolbox | -moz-window-button-box | -moz-window-button-box-maximized | -moz-window-button-close | -moz-window-button-maximize | -moz-window-button-minimize | -moz-window-button-restore | -moz-window-frame-bottom | -moz-window-frame-left | -moz-window-frame-right | -moz-window-titlebar | -moz-window-titlebar-maximized',
  '-webkit-appearance': 'auto | none | button | button-bevel | caps-lock-indicator | caret | checkbox | default-button | listbox | listitem | media-fullscreen-button | media-mute-button | media-play-button | media-seek-back-button | media-seek-forward-button | media-slider | media-sliderthumb | menulist | menulist-button | menulist-text | menulist-textfield | push-button | radio | searchfield | searchfield-cancel-button | searchfield-decoration | searchfield-results-button | searchfield-results-decoration | slider-horizontal | slider-vertical | sliderthumb-horizontal | sliderthumb-vertical | square-button | textarea | textfield | scrollbarbutton-down | scrollbarbutton-left | scrollbarbutton-right | scrollbarbutton-up | scrollbargripper-horizontal | scrollbargripper-vertical | scrollbarthumb-horizontal | scrollbarthumb-vertical | scrollbartrack-horizontal | scrollbartrack-vertical',
  'aspect-ratio': 'auto || <ratio>',

  'backdrop-filter': '<filter-function-list> | none',
  'backface-visibility': '<vis-hid>',
  'background': '[ <bg-layer> , ]* <final-bg-layer>',
  'background-attachment': '<attachment>#',
  'background-blend-mode': '<blend-mode>',
  'background-clip': '[ <box> | text | border-area ]#',
  'background-color': _color,
  'background-image': '<bg-image>#',
  'background-origin': '<box>#',
  'background-position': '<bg-position>#',
  'background-position-x': '[ center | [ [left|right|x-start|x-end]? <len-pct>? ]! ]#',
  'background-position-y': '[ center | [ [top|bottom|y-start|y-end]? <len-pct>? ]! ]#',
  'background-repeat': '<repeat-style>#',
  'background-size': '<bg-size>#',
  'baseline-shift': 'baseline | sub | super | <len-pct>',
  'baseline-source': 'auto | first | last',
  'block-size': _width,
  'border-collapse': 'collapse | separate',
  'border-image': '<border-image-source> || <border-image-slice> ' +
    '[ / <border-image-width> | / <border-image-width>? / <border-image-outset> ]? || ' +
    '<border-image-repeat>',
  'border-image-outset': '[ <len0+> | <num0+> ]{1,4}',
  'border-image-repeat': '[ stretch | repeat | round | space ]{1,2}',
  'border-image-slice': '<border-image-slice>',
  'border-image-source': '<image> | none',
  'border-image-width': '[ <len-pct0+> | <num0+> | auto ]{1,4}',
  'border-shape': 'none | [<basic-shape> <geometry-box>?]{1,2}',
  'border-spacing': '<len>{1,2}',
  //#region border shorthand
  'border': _borderShorthand,
  'border-block': _borderShorthand,
  'border-block-end': _borderShorthand,
  'border-block-start': _borderShorthand,
  'border-bottom': _borderShorthand,
  'border-inline': _borderShorthand,
  'border-inline-end': _borderShorthand,
  'border-inline-start': _borderShorthand,
  'border-left': _borderShorthand,
  'border-right': _borderShorthand,
  'border-top': _borderShorthand,
  //#endregion
  //#region border color
  'border-color': _color + '{1,4}',
  'border-block-color': _color + '{1,2}',
  'border-block-end-color': _color,
  'border-block-start-color': _color,
  'border-bottom-color': _color,
  'border-inline-color': _color + '{1,2}',
  'border-inline-end-color': _color,
  'border-inline-start-color': _color,
  'border-left-color': _color,
  'border-right-color': _color,
  'border-top-color': _color,
  //#endregion
  //#region border style
  'border-block-end-style': _lineStyle,
  'border-block-start-style': _lineStyle,
  'border-block-style': _lineStyle + '{1,2}',
  'border-bottom-style': _lineStyle,
  'border-inline-end-style': _lineStyle,
  'border-inline-start-style': _lineStyle,
  'border-inline-style': _lineStyle + '{1,2}',
  'border-left-style': _lineStyle,
  'border-right-style': _lineStyle,
  'border-style': _lineStyle + '{1,4}',
  'border-top-style': _lineStyle,
  //#endregion
  //#region border width
  'border-width': _lineWidth + '{1,4}',
  'border-block-end-width': _lineWidth,
  'border-block-start-width': _lineWidth,
  'border-block-width': _lineWidth + '{1,2}',
  'border-bottom-width': _lineWidth,
  'border-inline-end-width': _lineWidth,
  'border-inline-start-width': _lineWidth,
  'border-inline-width': _lineWidth + '{1,2}',
  'border-left-width': _lineWidth,
  'border-right-width': _lineWidth,
  'border-top-width': _lineWidth,
  //#endregion
  //#region border radius (shorthands)
  'border-radius': '<len-pct0+>{1,4} [ / <len-pct0+>{1,4} ]?',
  'border-block-end-radius': _borderTopRadius,
  'border-block-start-radius': _borderTopRadius,
  'border-bottom-radius': _borderTopRadius,
  'border-inline-end-radius': _borderTopRadius,
  'border-inline-start-radius': _borderTopRadius,
  'border-left-radius': _borderTopRadius,
  'border-right-radius': _borderTopRadius,
  'border-top-radius': '<len-pct0+>{1,2} [ / <len-pct0+>{1,2} ]?',
  //#endregion
  //#region border radius (single)
  'border-bottom-left-radius': _lenPct1or2,
  'border-bottom-right-radius': _lenPct1or2,
  'border-end-end-radius': _lenPct1or2,
  'border-end-start-radius': _lenPct1or2,
  'border-start-end-radius': _lenPct1or2,
  'border-start-start-radius': _lenPct1or2,
  'border-top-left-radius': _lenPct1or2,
  'border-top-right-radius': _lenPct1or2,
  //#endregion
  'bottom': '<top>',
  'box-decoration-break': 'slice | clone',
  'box-shadow': 'none | <shadow>#',
  'box-sizing': 'content-box | border-box',
  'break-after': '<break-inside> | always | left | right | page | column',
  'break-before': '<break-after>',
  'break-inside': 'auto | avoid | avoid-page | avoid-column',

  'caret': '<caret-color> || <caret-animation> || <caret-shape>',
  'caret-animation': 'auto | manual',
  'caret-color': 'auto | <color>',
  'caret-shape': 'auto | bar | block | underscore',
  'caption-side': 'top | bottom | inline-start | inline-end',
  'clear': 'none | right | left | both | inline-start | inline-end',
  'clip': 'rect() | auto',
  'clip-path': '<url> | [ <basic-shape> || <geometry-box> ] | none',
  'clip-rule': '<fill-rule>',
  'color': _color,
  'color-interpolation': 'auto | sRGB | linearRGB',
  'color-interpolation-filters': '<color-interpolation>',
  'color-profile': 1,
  'color-rendering': 'auto | optimizeSpeed | optimizeQuality',
  'color-scheme': 'normal | [ light | dark | <custom-ident> ]+ && only?',
  'column-count': 'auto | <int1+>',
  'column-fill': 'auto | balance | balance-all',
  'column-gap': 'normal | <len-pct0+> | <line-width>',
  'column-height': 'auto | <len0+>',
  'column-rule': '<rule>',
  'column-rule-break': '<row-rule-break>',
  'column-rule-color': '<rule-color>',
  'column-rule-inset': '<rule-inset>',
  'column-rule-inset-cap': _insetValue1or2,
  'column-rule-inset-cap-start': _insetValue,
  'column-rule-inset-cap-end': _insetValue,
  'column-rule-inset-junction': _insetValue1or2,
  'column-rule-inset-junction-start': _insetValue,
  'column-rule-inset-junction-end': _insetValue,
  'column-rule-inset-start': _insetValue,
  'column-rule-inset-end': _insetValue,
  'column-rule-style': '<rule-style>',
  'column-rule-visibility-items': _ruleVisibilityItems,
  'column-rule-width': '<rule-width>',
  'column-span': 'none | <int1+> | all | auto',
  'column-width': 'auto | <len0+>',
  'columns': '[ <column-width> || <column-count> ] [ / <column-height> ]?',
  'contain': 'none | strict | content | [ size || layout || style || paint ]',
  'contain-intrinsic-block-size': '<contain-intrinsic>',
  'contain-intrinsic-height': '<contain-intrinsic>',
  'contain-intrinsic-inline-size': '<contain-intrinsic>',
  'contain-intrinsic-size': '<contain-intrinsic>{1,2}',
  'contain-intrinsic-width': '<contain-intrinsic>',
  'container': '<container-name> [ / <container-type> ]?',
  'container-name': 'none | <ident-not-none>+',
  'container-type': 'normal | [ [ size | inline-size ] || scroll-state || anchored ]',
  'content': 'normal | none | <content-list> [ / <string> ]?',
  'content-visibility': 'auto | <vis-hid>',
  //#region corner (shorthands)
  'corner': '<border-radius> || <corner-shape>',
  'corner-top': '<border-top-radius> || <corner-top-shape>',
  'corner-bottom': _cornerTop,
  'corner-left': _cornerTop,
  'corner-right': _cornerTop,
  'corner-block-start': _cornerTop,
  'corner-block-end': _cornerTop,
  'corner-inline-start': _cornerTop,
  'corner-inline-end': _cornerTop,
  //#endregion
  //#region corner (single)
  'corner-top-left': '<border-top-left-radius> || <corner-top-left-shape>',
  'corner-top-right': _cornerTopLeft,
  'corner-bottom-left': _cornerTopLeft,
  'corner-bottom-right': _cornerTopLeft,
  'corner-end-end': _cornerTopLeft,
  'corner-end-start': _cornerTopLeft,
  'corner-start-end': _cornerTopLeft,
  'corner-start-start': _cornerTopLeft,
  //#endregion
  //#region corner shape (shorthands)
  'corner-shape': '<corner-shape-value>{1,4}',
  'corner-top-shape': '<corner-shape-value>{1,2}',
  'corner-block-end-shape': _cornerTopShape,
  'corner-block-start-shape': _cornerTopShape,
  'corner-bottom-shape': _cornerTopShape,
  'corner-inline-end-shape': _cornerTopShape,
  'corner-inline-start-shape': _cornerTopShape,
  'corner-left-shape': _cornerTopShape,
  'corner-right-shape': _cornerTopShape,
  //#endregion
  //#region corner shape (single)
  'corner-bottom-left-shape': _cornerShapeValue,
  'corner-bottom-right-shape': _cornerShapeValue,
  'corner-end-end-shape': _cornerShapeValue,
  'corner-end-start-shape': _cornerShapeValue,
  'corner-start-end-shape': _cornerShapeValue,
  'corner-start-start-shape': _cornerShapeValue,
  'corner-top-left-shape': _cornerShapeValue,
  'corner-top-right-shape': _cornerShapeValue,
  //#endregion
  'counter-increment': '<counter>',
  'counter-reset': '<counter>',
  'counter-set': '<counter>',
  'cursor': '[ [ <url> | image-set() ] [ <num> <num> ]? , ]* ' +
    '[ auto | default | none | context-menu | help | pointer | progress | wait | ' +
    'cell | crosshair | text | vertical-text | alias | copy | move | no-drop | ' +
    'not-allowed | grab | grabbing | e-resize | n-resize | ne-resize | nw-resize | ' +
    's-resize | se-resize | sw-resize | w-resize | ew-resize | ns-resize | ' +
    'nesw-resize | nwse-resize | col-resize | row-resize | all-scroll | ' +
    'zoom-in | zoom-out ]',
  'cx': '<x>',
  'cy': '<x>',

  'd': 1,
  'direction': 'ltr | rtl',
  'display': '[ <display-outside> || <display-inside> ] | ' +
    '<display-listitem> | <display-internal> | <display-box> | <display-legacy> | ' +
    '-webkit-box | -webkit-inline-box | -ms-flexbox', // deprecated and nonstandard
  'dominant-baseline': 'auto | text-bottom | alphabetic | ideographic | middle | central | ' +
    'mathematical | hanging | text-top',
  'dynamic-range-limit': '<dynamic-range> | <fn:dynaRange>',

  'empty-cells': 'show | hide',

  'field-sizing': 'fixed | content',
  'fill': '<paint>',
  'fill-opacity': '<num0-1>',
  'fill-rule': 'nonzero | evenodd',
  'filter': '<filter-function-list> | <ie-function> | none',
  'flex': 'none | [ <num>{1,2} || <flex-basis> ]',
  'flex-basis': 'content | <width>',
  'flex-direction': 'row | row-reverse | column | column-reverse',
  'flex-flow': '<flex-direction> || <flex-wrap>',
  'flex-grow': '<num>',
  'flex-shrink': '<num>',
  'flex-wrap': 'nowrap | [ wrap | wrap-reverse ] || balance',
  'float': 'left | right | none | inline-start | inline-end',
  'flood-color': 1,
  'flood-opacity': '<num0-1>',
  // matching no-pct first because Matcher doesn't retry for a longer match in nested definitions
  'font': '<font-short-tweak-no-pct>? <font-short-core> | ' +
    '[ <font-short-tweak-no-pct> || <pct> ]? <font-short-core> | ' +
    'caption | icon | menu | message-box | small-caption | status-bar',
  'font-family': '[ <generic-family> | <family-name> ]#',
  'font-feature-settings': '[ <ascii4> [ <int0+> | on | off ]? ]# | normal',
  'font-kerning': 'auto | normal | none',
  'font-language-override': 'normal | <string>',
  'font-optical-sizing': _autoNone,
  'font-palette': 'none | normal | light | dark | <custom-ident>',
  'font-size': '<absolute-size> | <relative-size> | <len-pct0+>',
  'font-size-adjust': 'none | [ex-height|cap-height|ch-width|ic-width|ic-height]? [from-font|<num0+>]',
  'font-stretch': '<font-stretch-named> | <pct>',
  'font-style': 'normal | italic | oblique <angle>?',
  'font-synthesis': 'none | [ weight || style ]',
  'font-synthesis-style': _autoNone,
  'font-synthesis-weight': _autoNone,
  'font-synthesis-small-caps': _autoNone,
  'font-variant': 'normal | none | [ ' +
    '<font-variant-ligatures> || <font-variant-alternates> || ' +
    '<font-variant-caps> || <font-variant-numeric> || <font-variant-east-asian> ]',
  'font-variant-alternates': '<font-variant-alternates> | normal',
  'font-variant-caps': '<font-variant-caps> | normal',
  'font-variant-east-asian': '<font-variant-east-asian> | normal',
  'font-variant-emoji': 'auto | text | emoji | unicode',
  'font-variant-ligatures': '<font-variant-ligatures> | normal | none',
  'font-variant-numeric': '<font-variant-numeric> | normal',
  'font-variant-position': 'normal | sub | super',
  'font-variation-settings': 'normal | [ <string> <num> ]#',
  'font-weight': 'normal | bold | bolder | lighter | <num1-1000>',
  'forced-color-adjust': 'auto | none | preserve-parent-color',

  'gap': '<column-gap>{1,2}',
  'grid':
    '<grid-template> | <grid-template-rows> / [ auto-flow && dense? ] <grid-auto-columns>? | ' +
    '[ auto-flow && dense? ] <grid-auto-rows>? / <grid-template-columns>',
  'grid-area': '<grid-line> [ / <grid-line> ]{0,3}',
  'grid-auto-columns': '<track-size>+',
  'grid-auto-flow': '[ row | column ] || dense',
  'grid-auto-rows': '<track-size>+',
  'grid-column': '<grid-line> [ / <grid-line> ]?',
  'grid-column-end': '<grid-line>',
  'grid-column-gap': -1,
  'grid-column-start': '<grid-line>',
  'grid-gap': -1,
  'grid-row': '<grid-line> [ / <grid-line> ]?',
  'grid-row-end': '<grid-line>',
  'grid-row-gap': -1,
  'grid-row-start': '<grid-line>',
  'grid-template': 'none | [ <grid-template-rows> / <grid-template-columns> ] | ' +
    '[ <line-names>? <string> <track-size>? <line-names>? ]+ [ / <explicit-track-list> ]?',
  'grid-template-areas': 'none | <string>+',
  'grid-template-columns': '<grid-template-rows>',
  'grid-template-rows': 'none | <track-list> | <auto-track-list> | ' +
    'subgrid [ <line-names> | repeat( [ <int1+> | auto-fill ] , <line-names>+ ) ]*',

  'hanging-punctuation': 'none | [ first || [ force-end | allow-end ] || last ]',
  'height': _width,
  'hyphenate-character': '<string> | auto',
  'hyphenate-limit-chars': '[ auto | <int> ]{1,3}',
  'hyphens': 'none | manual | auto',

  'image-orientation': 'from-image | none | [ <angle> || flip ]',
  'image-rendering': 'auto | smooth | high-quality | crisp-edges | pixelated | ' +
    'optimizeSpeed | optimizeQuality | -webkit-optimize-contrast',
  'image-resolution': 1,
  'inline-size': _width,
  'inset': '<top>{1,4}',
  'inset-block': '<top>{1,2}',
  'inset-block-end': '<top>',
  'inset-block-start': '<top>',
  'inset-inline': '<top>{1,2}',
  'inset-inline-end': '<top>',
  'inset-inline-start': '<top>',
  'interactivity': 'auto | inert',
  'interpolate-size': 'numeric-only | allow-keywords',
  'isolation': 'auto | isolate',

  'justify-content': 'normal | <content-distribution> | ' +
    '<overflow-position>? [ <content-position> | left | right ]',
  'justify-items': 'normal | stretch | anchor-center | <baseline-position> | [ <overflow-position>? <self-position> ] | [ legacy || [ left | right | center ] ]',
  'justify-self': 'auto | normal | stretch | anchor-center | <baseline-position> | <overflow-position>? [ <self-position> | left | right ]',

  'left': '<top>',
  'letter-spacing': '<len-pct> | normal',
  'lighting-color': _color,
  'line-height': '<line-height>',
  'line-break': 'auto | loose | normal | strict | anywhere',
  'list-style': '<list-style-position> || <list-style-image> || <list-style-type>',
  'list-style-image': '<image> | none',
  'list-style-position': 'inside | outside',
  'list-style-type': '<string> | disc | circle | square | decimal | decimal-leading-zero | ' +
    'lower-roman | upper-roman | lower-greek | lower-latin | upper-latin | armenian | ' +
    'georgian | lower-alpha | upper-alpha | none | symbols()',

  'math-depth': 'auto-add | add(<int>) | <int>',
  'math-shift': '<math-style>',
  'math-style': 'normal | compact',
  'margin': '<top>{1,4}',
  'margin-top': '<top>',
  'margin-bottom': '<top>',
  'margin-left': '<top>',
  'margin-right': '<top>',
  'margin-block': '<top>{1,2}',
  'margin-block-end': '<top>',
  'margin-block-start': '<top>',
  'margin-inline': '<top>{1,2}',
  'margin-inline-end': '<top>',
  'margin-inline-start': '<top>',
  'marker': -1,
  'marker-end': 1,
  'marker-mid': 1,
  'marker-start': 1,
  'mask': '[ [ none | <image> ] || <position> [ / <bg-size> ]? || <repeat-style> || ' +
    '<geometry-box> || [ <geometry-box> | no-clip ] || ' +
    '<compositing-operator> || <masking-mode> ]#',
  'mask-border': '<mask-border-source> ||' +
    '<mask-border-slice> [ / <mask-border-width> [ / <mask-border-outset> ]? ]? ||' +
    '<mask-border-repeat> || <mask-border-mode>',
  'mask-border-mode': '<mask-type>',
  'mask-border-outset': '[ <len> | <num> ]{1,4}',
  'mask-border-repeat': '[ stretch | repeat | round | space ]{1,2}',
  'mask-border-slice': '<num-pct>{1,4} fill?',
  'mask-border-source': 'none | <image>',
  'mask-border-width': '[ <len-pct> | <num> | auto ]{1,4}',
  'mask-clip': '[ <coord-box> | no-clip ]#',
  'mask-composite': '<compositing-operator>#',
  'mask-image': '[ none | <image> ]#',
  'mask-mode': '<masking-mode>#',
  'mask-origin': '<coord-box>#',
  'mask-position': '<position>#',
  'mask-repeat': '<repeat-style>#',
  'mask-size': '<bg-size>#',
  'mask-type': 'luminance | alpha',
  'max-height': '<max-width>',
  'max-width': 'none | <width-base>',
  'min-height': _width,
  'min-width': _width,
  'max-block-size': '<max-width>',
  'max-inline-size': '<max-width>',
  'min-block-size': _width,
  'min-inline-size': _width,
  'mix-blend-mode': '<blend-mode>',

  'object-fit': 'fill | contain | cover | none | scale-down',
  'object-position': '<position>',
  'object-view-box': 'none | inset() | rect() | xywh()',
  'offset':
    '[ <offset-position>? <offset-path> [<len-pct> || <offset-rotate>]? | <offset-position> ] ' +
    '[ / <offset-anchor> ]?',
  'offset-anchor': 'auto | <position>',
  'offset-distance': '<len-pct>',
  'offset-path': 'none | [ ray() | <url> | <basic-shape> ] || <coord-box>',
  'offset-position': 'auto | <position>',
  'offset-rotate': '[ auto | reverse ] || <angle>',
  'opacity': '<num0-1> | <pct>',
  'order': '<int>',
  'orphans': '<int>',
  'outline': '[ <color> | invert ] || [ auto | <line-style> ] || <line-width>',
  'outline-color': '<color> | invert',
  'outline-offset': '<len>',
  'outline-style': '<line-style> | auto',
  'outline-width': _lineWidth,
  'overflow': '<overflow>{1,2}',
  'overflow-anchor': _autoNone,
  'overflow-block': '<overflow>',
  'overflow-clip-margin': 'visual-box | <len0+>',
  'overflow-inline': '<overflow>',
  'overflow-wrap': 'normal | break-word | anywhere',
  'overflow-x': '<overflow>',
  'overflow-y': '<overflow>',
  'overscroll-behavior': '<overscroll>{1,2}',
  'overscroll-behavior-block': '<overscroll>',
  'overscroll-behavior-inline': '<overscroll>',
  'overscroll-behavior-x': '<overscroll>',
  'overscroll-behavior-y': '<overscroll>',

  'padding': '<len-pct0+>{1,4}',
  'padding-block': '<len-pct0+>{1,2}',
  'padding-block-end': _lenPct0plus,
  'padding-block-start': _lenPct0plus,
  'padding-bottom': _lenPct0plus,
  'padding-inline': '<len-pct0+>{1,2}',
  'padding-inline-end': _lenPct0plus,
  'padding-inline-start': _lenPct0plus,
  'padding-left': _lenPct0plus,
  'padding-right': _lenPct0plus,
  'padding-top': _lenPct0plus,
  'page': 'auto | <custom-ident>',
  'page-break-after': 'auto | always | avoid | left | right | recto | verso',
  'page-break-before': '<page-break-after>',
  'page-break-inside': 'auto | avoid',
  'paint-order': 'normal | [ fill || stroke || markers ]',
  'path-length': 'none | <num0+>',
  'perspective': 'none | <len0+>',
  'perspective-origin': '<position>',
  'place-content': '<align-content> <justify-content>?',
  'place-items': '[ normal | stretch | <baseline-position> | <self-position> ] ' +
    '[ normal | stretch | <baseline-position> | <self-position> ]?',
  'place-self': '<align-self> <justify-self>?',
  'pointer-events': 'auto | none | visiblePainted | visibleFill | visibleStroke | visible | ' +
    'painted | fill | stroke | all',
  'position': 'static | relative | absolute | fixed | sticky',
  'position-anchor': 'auto | <dashed-ident>',
  'position-area': 'auto | <position-area>',
  'position-try': '<position-try-order>? <position-try-fallbacks>',
  'position-try-order': 'normal | most-width | most-height | most-block-size | most-inline-size',
  'position-try-fallbacks': 'none | [[<dashed-ident> || <try-tactic>] | <position-area> ]#',
  'position-visibility': 'always | [ anchors-valid || anchors-visible || no-overflow ]',
  'print-color-adjust': 'economy | exact',

  'quotes': 1,

  'r': 1, // SVG
  'rx': '<x> | auto', // SVG
  'ry': '<rx>', // SVG
  'reading-flow': 'normal|source-order|flex-visual|flex-flow|grid-rows|grid-columns|grid-order',
  'reading-order': '<int>',
  'rendering-intent': 1, // SVG
  'resize': 'none | both | horizontal | vertical | block | inline',
  'right': '<top>',
  'rotate': 'none | [ x | y | z | <num>{3} ]? && <angle>',
  'row-gap': '<column-gap>',
  'row-rule': '<rule>',
  'row-rule-break': 'none | normal | intersection',
  'row-rule-color': '<rule-color>',
  'row-rule-inset': '<rule-inset>',
  'row-rule-inset-cap': _insetValue1or2,
  'row-rule-inset-cap-start': _insetValue,
  'row-rule-inset-cap-end': _insetValue,
  'row-rule-inset-junction': _insetValue1or2,
  'row-rule-inset-junction-start': _insetValue,
  'row-rule-inset-junction-end': _insetValue,
  'row-rule-inset-start': _insetValue,
  'row-rule-inset-end': _insetValue,
  'row-rule-style': '<rule-style>',
  'row-rule-visibility-items': _ruleVisibilityItems,
  'row-rule-width': '<rule-width>',
  'ruby-align': 'start | center | space-between | space-around',
  'ruby-position': 'alternate || [over|under] | inter-character',
  'rule': '<rule>',
  'rule-color': '<rule-color>',
  'rule-inset': `${_insetValue1or2} [ / ${_insetValue1or2}]?`,
  'rule-inset-cap': _insetValue1or2,
  'rule-inset-junction': _insetValue1or2,
  'rule-inset-start': _insetValue,
  'rule-inset-end': _insetValue,
  'rule-overlap': 'row-over-column | column-over-row',
  'rule-style': '<rule-style>',
  'rule-visibility-items': _ruleVisibilityItems,
  'rule-width': '<rule-width>',

  'scale': 'none | <num-pct>{1,3}',
  'scroll-behavior': 'auto | smooth',
  'scroll-margin': '<len>{1,4}',
  'scroll-margin-bottom': '<len>',
  'scroll-margin-left': '<len>',
  'scroll-margin-right': '<len>',
  'scroll-margin-top': '<len>',
  'scroll-margin-block': '<len>{1,2}',
  'scroll-margin-block-end': '<len>',
  'scroll-margin-block-start': '<len>',
  'scroll-margin-inline': '<len>{1,2}',
  'scroll-margin-inline-end': '<len>',
  'scroll-margin-inline-start': '<len>',
  'scroll-padding': '<top>{1,4}',
  'scroll-padding-left': '<top>',
  'scroll-padding-right': '<top>',
  'scroll-padding-top': '<top>',
  'scroll-padding-bottom': '<top>',
  'scroll-padding-block': '<top>{1,2}',
  'scroll-padding-block-end': '<top>',
  'scroll-padding-block-start': '<top>',
  'scroll-padding-inline': '<top>{1,2}',
  'scroll-padding-inline-end': '<top>',
  'scroll-padding-inline-start': '<top>',
  'scroll-snap-align': '[ none | start | end | center ]{1,2}',
  'scroll-snap-stop': 'normal | always',
  'scroll-snap-type': 'none | [ x | y | block | inline | both ] [ mandatory | proximity ]?',
  'scroll-target-group': 'none | auto',
  'scroll-timeline': '[ <scroll-timeline-name> <scroll-timeline-axis>? ]#',
  'scroll-timeline-axis': '<axis>#',
  'scroll-timeline-name': 'none | <dashed-ident>#',
  'scrollbar-color': 'auto | dark | light | <color>{2}',
  'scrollbar-gutter': 'auto | stable && both-edges?',
  'scrollbar-width': 'auto | thin | none',
  'shape-image-threshold': '<num-pct>',
  'shape-margin': '<len-pct>',
  'shape-rendering': 'auto | optimizeSpeed | crispEdges | geometricPrecision',
  'shape-outside': 'none | [ <basic-shape> || <shape-box> ] | <image>',
  'speak': 'auto | never | always',
  'stop-color': 1,
  'stop-opacity': '<num0-1>',
  'stroke': '<paint>',
  'stroke-dasharray': 'none | <dasharray>',
  'stroke-dashoffset': '<len-pct> | <num>',
  'stroke-linecap': 'butt | round | square',
  'stroke-linejoin': 'miter | miter-clip | round | bevel | arcs',
  'stroke-miterlimit': '<num0+>',
  'stroke-opacity': '<num0-1>',
  'stroke-width': '<len-pct> | <num>',

  'table-layout': 'auto | fixed',
  'tab-size': '<num> | <len>',
  'text-align': '<text-align> | justify-all',
  'text-align-last': '<text-align> | auto',
  'text-anchor': 'start | middle | end',
  'text-autospace': 'normal | <autospace> | auto',
  'text-box': 'normal | <text-box-trim> || <text-box-edge>',
  'text-box-edge': 'auto | text | [text|cap|ex] [text|alphabetic]',
  'text-box-trim': 'none | trim-start | trim-end | trim-both',
  'text-combine-upright': 'none | all | [ digits <int2-4>? ]',
  'text-decoration': '<text-decoration-line> || <text-decoration-style> || <color>',
  'text-decoration-color': _color,
  'text-decoration-line': 'none | [ underline || overline || line-through || blink ]',
  'text-decoration-skip': 'none | auto',
  'text-decoration-skip-ink': 'none | auto | all',
  'text-decoration-style': 'solid | double | dotted | dashed | wavy',
  'text-decoration-thickness': 'auto | from-font | <len-pct>',
  'text-emphasis': '<text-emphasis-style> || <color>',
  'text-emphasis-color': _color,
  'text-emphasis-style': 'none | <string> | ' +
    '[ [ filled | open ] || [ dot | circle | double-circle | triangle | sesame ] ]',
  'text-emphasis-position': '[ over | under ] && [ right | left ]?',
  'text-fit': '[none|grow|shrink] [consistent|per-line|per-line-all]? <pct>?',
  'text-indent': '<len-pct> && hanging? && each-line?',
  'text-justify': 'auto | none | inter-word | inter-character',
  'text-orientation': 'mixed | upright | sideways',
  'text-overflow': 'clip | ellipsis',
  'text-rendering': 'auto | optimizeSpeed | optimizeLegibility | geometricPrecision',
  'text-shadow': 'none | [ <color>? && <len>{2,3} ]#',
  'text-size-adjust': 'auto | none | <pct0+>',
  'text-spacing-trim': 'auto|space-all|normal|space-first|trim-start|trim-both|trim-all',
  'text-transform': 'none | math-auto | ' +
    '[ capitalize|uppercase|lowercase ] || full-width || full-size-kana',
  'text-underline-offset': '<len-pct> | auto',
  'text-underline-position': 'auto | [ under || [ left | right ] ]',
  'text-wrap': 'wrap | nowrap | balance | stable | pretty',
  'text-wrap-mode': 'wrap | nowrap',
  'text-wrap-style': 'auto | balance | stable | pretty',
  'timeline-scope': 'none | all | <dashed-ident>#',
  'top': 'auto | <len-pct> | anchor() | anchor-size()',
  'touch-action': 'auto|none|pan-x|pan-y|pan-left|pan-right|pan-up|pan-down|manipulation',
  'transform': 'none | <fn:transform>+',
  'transform-box': 'content-box | border-box | fill-box | stroke-box | view-box',
  'transform-origin': '[ left | center | right | <len-pct> ] ' +
    '[ top | center | bottom | <len-pct> ] <len>? | ' +
    '[ left | center | right | top | bottom | <len-pct> ] | ' +
    '[ [ center | left | right ] && [ center | top | bottom ] ] <len>?',
  'transform-style': 'flat | preserve-3d',
  'transition': '[ [ none | [ all | <custom-ident> ]# ] || <time> || <timing-function> || <time> || <txbhv> ]#',
  'transition-behavior': '<txbhv>#',
  'transition-delay': '<time>#',
  'transition-duration': '<time>#',
  'transition-property': 'none | [ all | <custom-ident> ]#',
  'transition-timing-function': '<timing-function>#',
  'translate': 'none | <len-pct> [ <len-pct> <len>? ]?',

  'unicode-range': '<unicode-range>#',
  'unicode-bidi': 'normal | embed | isolate | bidi-override | isolate-override | plaintext',
  'user-select': 'auto | text | none | contain | all',

  'vertical-align': 'auto | use-script | baseline | sub | super | top | text-top | ' +
    'central | middle | bottom | text-bottom | <len-pct>',
  'view-timeline': '[ <view-timeline-name> [ <view-timeline-axis> || <view-timeline-inset> ]? ]#',
  'view-timeline-axis': '<axis>#',
  'view-timeline-inset': '[ [ auto | <len-pct> ]{1,2} ]#',
  'view-timeline-name': '[ none | <dashed-ident> ]#',
  'view-transition-class': 'none | <ident-not-none>+',
  'view-transition-name': 'none | auto | match-element | <custom-ident>',
  'visibility': '<vis-hid> | collapse',

  'white-space': 'normal | pre | pre-wrap | pre-line | <white-space-collapse> || <text-wrap-mode>',
  'white-space-collapse': 'collapse|discard|preserve|preserve-breaks|preserve-spaces|break-spaces',
  'widows': '<int>',
  'width': 'auto | <width-base>',
  'will-change': 'auto | <animateable-feature>#',
  'word-break': 'normal | keep-all | break-all | break-word',
  'word-spacing': '<len-pct> | normal',
  'word-wrap': 'normal | break-word | anywhere',
  'writing-mode': 'horizontal-tb | vertical-rl | vertical-lr | sideways-rl | sideways-lr',

  'x': '<len-pct> | <num>',
  'y': '<x>',
  'z-index': '<int> | auto',
  'zoom': '<num> | <pct> | normal',

  // nonstandard https://compat.spec.whatwg.org/
  '-webkit-box-reflect': '[ above | below | right | left ]? <len>? <image>?',
  '-webkit-text-fill-color': _color,
  '-webkit-text-stroke': '<line-width> || <color>',
  '-webkit-text-stroke-color': _color,
  '-webkit-text-stroke-width': _lineWidth,
  '-webkit-user-modify': 'read-only | read-write | write-only',
};
Properties['-ms-appearance'] = 'icon | ' + (
  Properties['-o-appearance'] = 'none | window | desktop | workspace | document | tooltip | dialog | button | push-button | hyperlink | radio | radio-button | checkbox | menu-item | tab | menu | menubar | pull-down-menu | pop-up-menu | list-menu | radio-group | checkbox-group | outline-tree | range | field | combo-box | signature | password | normal'
);

export default Properties;
